# [target.x86_64-unknown-linux-gnu]
# linker = "x86_64-unknown-linux-gnu-gcc"
[alias]
snapshot = "insta test --review"
build-linux = "build --release --target=x86_64-unknown-linux-musl"
build-win = "build --release --target=x86_64-pc-windows-gnu"
