name: neolisp Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{matrix.rust}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
        rust: [stable, nightly]
        include:
          - rust: stable
            can-fail: false
          - rust: nightly
            can-fail: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Install Rust
      uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt,clippy
    - name: Environment Information
      shell: bash
      run: |
        ls -la &&
        printenv | sort -u
    - name: Debug Docs.md
      shell: bash
      run: |
        echo "Checking Docs.md"
        if [ -f Docs.md ]; then
          echo "Docs.md exists"
          cat Docs.md
        else
          echo "Docs.md does not exist"
          exit 1
        fi
    - name: Toolchain Information
      run: |
        rustc --version
        rustfmt --version
        rustup --version
        cargo --version
    - name: Check Formatting
      if: matrix.rust == 'stable'
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -- -D clippy::all
      continue-on-error: ${{ matrix.can-fail }}
    - name: Rust Test Build
      run: cargo test
